---
title: "Analysis Bulgaria"
output: html_notebook
---

```{r}
bul <- readxl::read_xlsx("C:/Users/User/Documents/UNITN/Computational social science/bulgaria/final_CITIES.xlsx")

bul$activity_rate <- as.double(bul$activity_rate)
bul$labour_force_thousands <- as.double(bul$labour_force_thousands)
bul$employment_rate <- as.double(bul$employment_rate)
bul$foreign_direct_investment_euro <- as.double(bul$foreign_direct_investment_euro)

apply(bul[,-1], 2, mean)
plot(apply(bul[,-1], 2, mean))
```

Taking a look at the correlation plot.

```{r}
library(ggplot2)
library(ggcorrplot)
ggcorrplot(cor(bul[,-1]), hc.order = TRUE, type = "lower", tl.srt = 90, tl.cex = 8)
cor_pmat(bul[,-1])

```

PCA

```{r}
pr.out <- prcomp(bul[,-1] , scale = TRUE)
plot(pr.out)
pr.out$rotation
dim(pr.out$x)
biplot(pr.out , scale = 0)

pr.out$rotation = -pr.out$rotation
pr.out$x = -pr.out$x
biplot(pr.out , scale = 0)

pr.out$sdev

#The variance explained by each principal component is obtained by squaring
#these:
pr.var <- pr.out$sdev^2
pr.var
#explained var
pve <- pr.var / sum(pr.var)
pve
```

```{r}
library(ggpubr)


p1 <- ggplot(data = as.data.frame(pve), aes(x = seq(1:28), y = pve)) + 
        geom_point() +
        #geom_line() +
        #geom_segment(aes(x = 5, y = 0, xend = 5, yend = pve[5])) +
        #geom_segment(aes(x = 0, y = pve[5], xend = 5, yend = pve[5])) +
        xlab("Principal Component") +
        ylab("Proportion of Variance Explained") +
        scale_x_continuous(expand = c(0.01,0)) +
        scale_y_continuous(expand = c(0.05, 0), limits = c(0,1)) +
        theme_classic() 

p2 <- ggplot(data = as.data.frame(cumsum(pve)), aes(x = seq(1:28), y = cumsum(pve))) + 
        geom_point() +
        geom_line() +
        geom_segment(aes(x = 5, y = 0, xend = 5, yend = cumsum(pve)[5])) +
        geom_segment(aes(x = 0, y = cumsum(pve)[5], xend = 5, yend = cumsum(pve)[5])) +
        xlab("Principal Component") +
        ylab("Cumulative Proportion of Variance Explained") +
        scale_x_continuous(expand = c(0,0)) +
        scale_y_continuous(expand = c(0, 0)) +
        theme_classic()

ggarrange(p1, p2)
```


```{r}
comp <- data.frame(pr.out$x[,1:5])

#write.csv(comp, "C:/Users/User/Documents/UNITN/Computational social science/bulgariafirst5PCs.csv")
plot(comp, pch=16, col=rgb(0,0,0,0.5))
#outlier in all the dimensions, and some grouping in the different projections.

summary(pr.out)
bul_transform <- as.data.frame(-pr.out$x[,1:5])
```

#Clustering k-means

```{r}
library(factoextra)
fviz_nbclust(bul_transform, kmeans, method = 'wss')
fviz_nbclust(bul_transform, kmeans, method = 'silhouette')
fviz_nbclust(bul_transform, kmeans, method = 'gap_stat')


```

```{r}
k = 4
kmeans_bul = kmeans(bul_transform, centers = k, nstart = 20)
fviz_cluster(kmeans_bul, data = bul_transform) + theme_classic()
```

```{r}
set.seed(21)
k <- kmeans(comp, 4, nstart=25, iter.max=1000)
library(RColorBrewer)
library(scales)
palette(alpha(brewer.pal(9,'Set1'), 0.5))
plot(comp, col=k$clust, pch=16)

clusters_kmeans4 <- k$cluster
```

```{r}
bul_with_labels <- bul[,]
bul_with_labels$kmeans4 <- as.factor(clusters_kmeans4)

scaled <- as.data.frame(scale(bul_with_labels[,-c(1,30)]))
scaled$Region <- bul$Region
scaled$kmeans4 <- as.factor(clusters_kmeans4)
```

Random forest with previously found clusters. Turning to supervised method to see variable importance

```{r}
library(randomForest)
set.seed(21)
rf_bul <- randomForest(kmeans4 ~.-Region, data = scaled, mtry = 9, importance = TRUE) 
importance(rf_bul)
varImpPlot(rf_bul)
```

```{r}
boxplot(bul_with_labels$connected_to_wastewater_collecting ~ bul_with_labels$kmeans4,
        xlab='Cluster', ylab='connected_to_wastewater_collecting',
        main='connected_to_wastewater_collecting by Cluster')
boxplot(bul$employment_rate ~ bul_with_labels$kmeans4,
        xlab='Cluster', ylab='employment_rate',
        main='employment_rate by Cluster')
```

```{r}
rownames(scaled) <- scaled$Region
rownames(bul_transform) <- scaled$Region
```

#Hierarchical clustering

```{r}
set.seed(21)
distmatrix2 <- dist(bul_transform)
hc2 <- hclust(distmatrix2, method = "complete")
plot(hc2, labels = scaled$Region)
labs_pca_hc4 <- cutree(hc2, 4)


#hc2$labels <- as.vector(bul_with_labels[hc2$order, 'Region'])
fviz_dend(hc2,cex = 0.5, k = 4,rect = TRUE)
```

```{r}
#See var importance when hclust
set.seed(21)
rf_bul2 <- randomForest(labs_pca_hc4 ~.-Region - kmeans4, data = scaled, mtry = 9, importance = TRUE)
importance(rf_bul2)
varImpPlot(rf_bul2)
```

Align clusters of the two methods

```{r}
i = labs_pca_hc4 == 1
j = labs_pca_hc4 == 3
v = labs_pca_hc4 == 4
labs_pca_hc4[i] = 3
labs_pca_hc4[j] = 4
labs_pca_hc4[v] = 1
```

```{r}
labs_pca_hc4 == clusters_kmeans4
sum(labs_pca_hc4 == clusters_kmeans4)
table(labs_pca_hc4, clusters_kmeans4)
bul_with_labels$labs_pca_hc4 <- as.factor(labs_pca_hc4)
scaled$labs_pca_hc4 <- as.factor(labs_pca_hc4)
```

```{r}
mclust::adjustedRandIndex(clusters_kmeans4, labs_pca_hc4)
#describe what it is and how it is calculated
```

```{r}
par(mfrow = c(1,2))

boxplot(bul_with_labels$connected_to_wastewater_collecting ~ bul_with_labels$kmeans4,
        xlab='Cluster', ylab='connected_to_wastewater_collecting',
        main='connected_to_wastewater_collecting by Cluster kmeans')
boxplot(bul_with_labels$connected_to_wastewater_collecting ~ bul_with_labels$labs_pca_hc4,
        xlab='Cluster', ylab='connected_to_wastewater_collecting',
        main='connected_to_wastewater_collecting by Cluster hclust')

boxplot(bul$employment_rate ~ bul_with_labels$kmeans4,
        xlab='Cluster', ylab='employment_rate',
        main='employment_rate by Cluster kmeans')

boxplot(bul$employment_rate ~ bul_with_labels$labs_pca_hc4,
        xlab='Cluster', ylab='employment_rate',
        main='employment_rate by Cluster hclust')

boxplot(bul$activity_rate ~ bul_with_labels$kmeans4,
        xlab='Cluster', ylab='activity_rate',
        main='activity_rate by Cluster kmeans')

boxplot(bul$activity_rate ~ bul_with_labels$labs_pca_hc4,
        xlab='Cluster', ylab='activity_rate',
        main='activity_rate by Cluster hclust')


par(mfrow = c(1,1))
```

```{r}
ggplot(bul_with_labels, aes(Population2021, colour = kmeans4)) +
        geom_density()

ggplot(bul_with_labels, aes(x = kmeans4, y = Population2021)) +
        geom_bar(
                aes(color = Region, fill = Region),
                stat = "summary", position = position_stack()
        ) +
        theme_classic()

ggplot(bul_with_labels, aes(x = kmeans4, y = activity_rate)) +
        geom_bar(
                aes(fill = kmeans4),
                #aes(color = Region, fill = Region),
                stat = "summary", position = position_stack()
        ) +
        theme_classic()

ggplot(bul_with_labels, aes(x = kmeans4, y = connected_to_wastewater_collecting)) +
        geom_bar(
                aes(fill = kmeans4),
                #aes(color = Region, fill = Region),
                stat = "summary", position = position_stack()
        ) +
        theme_classic()

```

```{r}
#To see which cities are classified differently
bul_with_labels$Region[bul_with_labels$kmeans4 == 2 & bul_with_labels$labs_pca_hc4 == 3]

```


#Lasso regression

```{r}
#Trying lasso regression on one of the most important variables for both kmeans and hclust: employment rate!
library(glmnet)

y <- scaled$employment_rate

set.seed(21)
tr <- sample(1:nrow(scaled), 0.8*nrow(scaled))
ts <- -tr
y_test <- y[ts]
y_train <- y[tr]

x <- model.matrix(employment_rate ~ .-Region-labs_pca_hc4 - kmeans4, data = scaled)[,-c(16,29,30,31)]

x_train <- model.matrix(employment_rate ~ .-Region-labs_pca_hc4 - kmeans4, data = scaled[tr,])[,-c(16,29,30,31)]
x_test <- model.matrix(employment_rate ~ .-Region-labs_pca_hc4 - kmeans4, data = scaled[ts,])[,-c(16,29,30,31)]
```

```{r}
set.seed(21)
cv.las <- cv.glmnet(x_train, y_train, alpha = 1, nfolds = 5)

las <- glmnet(x_train, y_train, alpha = 1)

plot(cv.las)
bestlam = cv.las$lambda.min

las_predict <- predict(las, s = bestlam, newx = x_test)
mean((las_predict - y_test)^2) #test error based on one split train-test
```

```{r}
#Fit lasso on full dataset
out <- glmnet(x, y, alpha = 1)
las_pred <- predict(out, type = "coefficients", s = bestlam)[1:28,]
las_pred
 
print(las_pred[las_pred != 0]) # These are the most important variables
#Again we see that activity rate and wastewater is very important, but also ecological assets

plot(out, xvar = "lambda", label = TRUE)
```
```{r}
set.seed(21)
cv.ridg <- cv.glmnet(x_train, y_train, alpha = 0, nfolds = 5)

ridg <- glmnet(x_train, y_train, alpha = 0)

plot(cv.ridg)
bestlam = cv.ridg$lambda.min

ridg_predict <- predict(ridg, s = bestlam, newx = x_test)
mean((ridg_predict - y_test)^2)

out <- glmnet(x, y, alpha = 0)
ridg_pred <- predict(out, type = "coefficients", s = bestlam)[1:28,]
ridg_pred
 
plot(out, xvar = "lambda", label = TRUE)

```




```{r}
write.csv(bul_with_labels, "C:/Users/User/Documents/UNITN/Computational social science/bulgaria/bul_with_labels.csv")
```







